services:
  - type: web
    name: server_viewdiful
    env: go
    buildCommand: go build -o app .
    startCommand: ./app
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
